# This workflow warns when issues have had no activity for a specified amount of time.
# For more information, see:
# https://github.com/actions/stale
name: Mark Stale Issues

on:
  # Enable manual run from the Actions tab.
  workflow_dispatch:
  # Scheduled to run at 12:00 on every 1st of the month.
  schedule:
    - cron: '0 12 1 * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      # PR permissions can be added here
      issues: write

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          remove-stale-when-updated: false
          include-only-assigned: true
          # Disable closing issues
          days-before-close: -1
          stale-issue-label: 'stale'
          # Ignores comments as activity, only looks at date of issue creation.
          ignore-updates: true
          # Ignore developer staff and frequent contributors
          exempt-assignees: 'kyleecodes, swetha-charles, eleanorreem, annarhughes, tarebyte'
          stale-issue-message: 'As per Chayn policy, after 60 days of inactivity, we will be unassigning this issue to open it back up for contributors. Please comment to be re-assigned. Thank you for your interest in contributing to Chayn!'
